### ISSUE TITLE
What is update rate?

### ISSUE THREAD

**Issue by XinhaoMei** [Anjaney1999/image-captioning-seqgan#4]
Hi, thanks for your great work! 
I am confused what the update rate is in Rollout and its function? I didn't find that in paper, could you please help me? Thanks!

**Comment by Anjaney1999** [comment]
Apologies for the late reply. That was taken from https://github.com/X-czh/SeqGAN-PyTorch. Also, I do not remember, but I believe the author of the original SeqGAN paper also did that in his/her implementation. Apologies for not being of more help!

**Comment by XinhaoMei** [comment]
Received. Thank you very much!
